services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${APP_DB_PORT}:{APP_DB_PORT}"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
