name: Docker Image CI

env:
  REPOSITORY: cicd-exercises
  TRIVY_IMAGE_RESULTS: trivy-image-results.sarif
  TRIVY_REPO_RESULTS: trivy-repo-results.sarif
  TRIVY_IAC_RESULTS: trivy-iac-results.sarif

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git commit SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./EX04-CI-with-GitHubActions
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:${{ steps.get_sha.outputs.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:${{ steps.get_sha.outputs.sha }}'
          format: 'sarif'
          output: ${{ env.TRIVY_IMAGE_RESULTS }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: ${{ env.TRIVY_REPO_RESULTS }}
          severity: 'CRITICAL'

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: ${{ env.TRIVY_IAC_RESULTS }}
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab (Image)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.TRIVY_IMAGE_RESULTS }}
          category: 'container'
      - name: Upload Trivy scan results to GitHub Security tab (Code)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.TRIVY_REPO_RESULTS }}
          category: 'code'
      - name: Upload Trivy scan results to GitHub Security tab (IaC)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.TRIVY_IAC_RESULTS }}
          category: 'iac'

