name: Docker Image CI

variables:
  - name: repository
    value: cicd-exercises

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git commit SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./EX04-CI-with-GitHubActions
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ variables.repository }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ variables.repository }}:${{ steps.get_sha.outputs.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ variables.repository }}:${{ steps.get_sha.outputs.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-repo-results.sarif'
          severity: 'CRITICAL'

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-iac-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab (Image)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'container'
      - name: Upload Trivy scan results to GitHub Security tab (Code)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-repo-results.sarif'
          category: 'code'
      - name: Upload Trivy scan results to GitHub Security tab (IaC)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-iac-results.sarif'
          category: 'code'

